spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sroba1993/Config
#Local configuration
#          uri: file:///D:\Proyectos\ADN - Scotiabank\Config

server:
  port: 8888

